// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcY-kBdfBau65gWQrdhGtp8KUnMAOZVqE',
    appId: '1:163355634622:web:653f47310dbed9de53e7ef',
    messagingSenderId: '163355634622',
    projectId: 'myapp1-1128f',
    authDomain: 'myapp1-1128f.firebaseapp.com',
    storageBucket: 'myapp1-1128f.appspot.com',
    measurementId: 'G-NNKP63P5LB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_X6vHbmDf4zswMIZqNL1L_RyjaxsSFe0',
    appId: '1:163355634622:android:acef08233e64716d53e7ef',
    messagingSenderId: '163355634622',
    projectId: 'myapp1-1128f',
    storageBucket: 'myapp1-1128f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVMh_N-59dr-QbWzt46Wb2BJLO_7axwFQ',
    appId: '1:163355634622:ios:1c484f94f07fcd3b53e7ef',
    messagingSenderId: '163355634622',
    projectId: 'myapp1-1128f',
    storageBucket: 'myapp1-1128f.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVMh_N-59dr-QbWzt46Wb2BJLO_7axwFQ',
    appId: '1:163355634622:ios:3b10c5bf60f8a12a53e7ef',
    messagingSenderId: '163355634622',
    projectId: 'myapp1-1128f',
    storageBucket: 'myapp1-1128f.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
